--B. Runner and Customer Experience
--1. How many runners signed up for each 1 week period? (i.e. week starts 2021-01-01)
SELECT DATEDIFF(DAY, '2021-01-01', REGISTRATION_DATE)/7 + 1 AS SIGNUP_WEEK,
	   COUNT(DISTINCT RUNNER_ID) AS COUNT_RUNNERS
FROM RUNNERS
GROUP BY DATEDIFF(DAY, '2021-01-01', REGISTRATION_DATE)/7 + 1
ORDER BY SIGNUP_WEEK
GO

--2. What was the average time in minutes it took for each runner to arrive at the Pizza Runner HQ to pickup the order?
SELECT RUNNER_ID, ROUND(AVG(DATEDIFF(MINUTE, ORDER_DATE, PICKUP_TIME)), 0) AS AVG_TIME
FROM #RUNNER_ORDERS_TEMP RO
JOIN #CUSTOMER_ORDERS_TEMP CO ON RO.ORDER_ID = CO.ORDER_ID
WHERE CANCELLATION IS NULL
GROUP BY RUNNER_ID
GO

--3. Is there any relationship between the number of pizzas and how long the order takes to prepare?
SELECT NUMBER_OF_PIZZAS,
       ROUND(AVG(TIME_PREPARE), 0) AS AVG_TIME_PREPARE
FROM (SELECT CO.ORDER_ID, 
      COUNT(PIZZA_ID) AS NUMBER_OF_PIZZAS,
      DATEDIFF(MINUTE, ORDER_DATE, PICKUP_TIME) AS TIME_PREPARE
      FROM #RUNNER_ORDERS_TEMP RO
      JOIN #CUSTOMER_ORDERS_TEMP CO ON RO.ORDER_ID = CO.ORDER_ID
      WHERE CANCELLATION IS NULL
      GROUP BY CO.ORDER_ID, ORDER_DATE, PICKUP_TIME) AS T
GROUP BY NUMBER_OF_PIZZAS
ORDER BY NUMBER_OF_PIZZAS
GO

SELECT CO.ORDER_ID, 
       COUNT(PIZZA_ID) AS NUMBER_OF_PIZZAS,
       DATEDIFF(MINUTE, ORDER_DATE, PICKUP_TIME) AS TIME_PREPARE
FROM #RUNNER_ORDERS_TEMP RO
JOIN #CUSTOMER_ORDERS_TEMP CO ON RO.ORDER_ID = CO.ORDER_ID
WHERE CANCELLATION IS NULL
GROUP BY CO.ORDER_ID, ORDER_DATE, PICKUP_TIME
ORDER BY COUNT(PIZZA_ID)
GO

--4. What was the average distance travelled for each customer?
SELECT CUSTOMER_ID, ROUND(AVG(DISTANCE), 2) AS AVG_DISTANCE
FROM #CUSTOMER_ORDERS_TEMP CO
JOIN #RUNNER_ORDERS_TEMP RO ON CO.ORDER_ID = RO.ORDER_ID
WHERE CANCELLATION IS NULL
GROUP BY CUSTOMER_ID
GO

--5. What was the difference between the longest and shortest delivery times for all orders?
SELECT MAX(DURATION) - MIN(DURATION) AS DELIVERY_TIME_DIFF
FROM #RUNNER_ORDERS_TEMP
GO

--6. What was the average speed for each runner for each delivery and do you notice any trend for these values?
SELECT RUNNER_ID, ORDER_ID, DISTANCE, ROUND(DISTANCE * 60 / DURATION, 2) AS AVG_SPEED
FROM #RUNNER_ORDERS_TEMP RO 
WHERE CANCELLATION IS NULL
ORDER BY RUNNER_ID
GO

--7. What is the successful delivery percentage for each runner?
SELECT RUNNER_ID, ROUND(COUNT(DISTANCE) * 100 / COUNT(ORDER_ID), 2) AS SUCCESS_PERCENTAGE
FROM #RUNNER_ORDERS_TEMP
GROUP BY RUNNER_ID
GO